name: Test Project

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for test scripts
        run: |
          if [ ! -f "tests/run_tests.sh" ]; then
            echo "No test scripts found" > napaka.txt
            exit 1
          fi
        continue-on-error: false
        id: check_tests
      - name: Upload error if tests not found
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: napaka.txt

  run-tests:
    runs-on: [self-hosted, linux]
    needs: check-tests
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          bash tests/run_tests.sh
        continue-on-error: false
        id: run_tests
      - name: Upload error if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: napaka.txt
