name: Test and Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for test scripts
        run: |
          if [ ! -f "tests/run_tests.sh" ]; then
            echo "No test scripts found" > napaka.txt
            exit 1  # Fail the job if test script is not found
          fi
          echo "Test scripts found" > napaka.txt

      - name: Always upload artifact (napaka.txt)
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: napaka.txt

  deploy:
    runs-on: [self-hosted, linux]
    needs: check-tests
    if: success()
    strategy:
      matrix:
        os: [ubuntu-latest, centos:8]
        tag: [latest, v1.0, v2.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load error artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: error
          path: ./  # Path where artifact will be downloaded

        - name: Check for errors
        run: |
          if [ -f "./napaka.txt" ]; then
            if grep -q "No test scripts found" ./napaka.txt; then  # Look for the error message
              cat ./napaka.txt
              exit 1  # Only fail the job if the error message is found
            else
              echo "Test scripts found, continuing with deployment."
            fi
          else
            echo "No napaka.txt file found, continuing."
          fi


      - name: Build Docker image
        run: |
          docker build -t username/my-repo:${{ matrix.tag }} .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push username/my-repo:${{ matrix.tag }}
