name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Test Project"]
    types:
      - completed

jobs:
  check-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    runs-on: [self-hosted, linux]
    needs: check-deploy
    if: success()
    strategy:
      matrix:
        os: [ubuntu-latest, centos:8]  # Example matrix of different OSs
        tag: [latest, v1.0, v2.0]       # Example matrix of different tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load error artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: error
          path: ./error_artifacts

      - name: Check for errors
        run: |
          if [ -f "./error_artifacts/napaka.txt" ]; then
            cat ./error_artifacts/napaka.txt
            exit 1
          fi

      - name: Build Docker image
        run: |
          docker build -t username/my-repo:${{ matrix.tag }} .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push username/my-repo:${{ matrix.tag }}
