name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Test Project"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    needs: check-tests
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Load error artifact
        uses: actions/download-artifact@v4
        with:
          name: error
          path: .

      - name: Check for errors
        run: |
          if [ -f "napaka.txt" ]; then
            cat napaka.txt
            exit 1
          fi

      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push my-image
