name: 28542 Test

on:
  push:
    branches: [main]

jobs:
  check-tests:
    runs-on: self-hosted
    outputs:
      error: ${{ steps.check.outputs.error }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for test scripts
        id: check
        run: |
          if [ ! -f "./tests/run_tests.sh" ]; then
            echo "Test script not found!" >&2
            echo "Test script not found!" > napaka.txt
            exit 1
          fi
          echo "error=" >> $GITHUB_OUTPUT

      - name: Upload error artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-error
          path: napaka.txt

  run-tests:
    needs: check-tests
    runs-on: self-hosted
    if: ${{ needs.check-tests.result == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download potential error file
        uses: actions/download-artifact@v4
        with:
          name: test-error
          path: ./error_check

      - name: Check for previous errors
        run: |
          if [ -f ./error_check/napaka.txt ]; then
            echo "Found previous error, aborting tests"
            cat ./error_check/napaka.txt
            exit 1
          fi

      - name: Run tests
        run: |
          chmod +x ./tests/run_tests.sh
          ./tests/run_tests.sh
