name: 28542 Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted
    needs: [28542 Test]
    if: ${{ success() }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yourdockerhubuser/yourapp:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push yourdockerhubuser/yourapp:latest
